export const SET_FOUND_BOOKS = 'SET_FOUND_BOOKS';
export const ADD_BOOK_TO_RECOMMENDATIONS = 'ADD_BOOK_TO_RECOMMENDATIONS';
export const CLEAR_FOUND_BOOKS = 'CLEAR_FOUND_BOOKS';
export const REMOVE_BOOK_FROM_RECOMMENDATIONS =
  'REMOVE_BOOK_FROM_RECOMMENDATIONS';
export const CLEAR_RECOMMENDATIONS = 'CLEAR_RECOMMENDATIONS';
export const EDIT_RECOMMENDATION = 'EDIT_RECOMMENDATION';
export const SET_FRIEND_NAME = 'SET_FRIEND_NAME';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_IS_SIGNED_IN = 'SET_IS_SIGNED_IN';
export const SET_GAPI_CLIENT = 'SET_GAPI_CLIENT';
export const SET_GOOGLE_AUTH = 'SET_GOOGLE_AUTH';
