export const SET_FOUND_BOOKS = 'SET_FOUND_BOOKS';
export const ADD_BOOK_TO_RECOMMENDATIONS = 'ADD_BOOK_TO_RECOMMENDATIONS';
export const CLEAR_FOUND_BOOKS = 'CLEAR_FOUND_BOOKS';
export const REMOVE_BOOK_FROM_RECOMMENDATIONS =
  'REMOVE_BOOK_FROM_RECOMMENDATIONS';
export const CLEAR_RECOMMENDATIONS = 'CLEAR_RECOMMENDATIONS';
export const EDIT_RECOMMENDATION = 'EDIT_RECOMMENDATION';
